# Generated by Django 5.2.8 on 2025-12-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Canonical city name (e.g. San Carlos de Bariloche)', max_length=255)),
                ('slug', models.SlugField(help_text='Unique slug generated from name (used in URLs)', max_length=255, unique=True)),
                ('country', models.CharField(help_text='Country name (e.g. Argentina)', max_length=100)),
                ('continent', models.CharField(blank=True, help_text='Continent (e.g. South America)', max_length=50, null=True)),
                ('hero_image', models.ImageField(blank=True, help_text='Main image used on destination cards and hero sections', null=True, upload_to='destinations/hero/')),
                ('is_active', models.BooleanField(default=True, help_text='Controls visibility of the destination in the frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['name'],
            },
        ),
    ]
