# Generated by Django 5.2.8 on 2025-12-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='hero_image',
            field=models.URLField(blank=True, help_text='Cloudinary URL for destination hero image'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
