# Generated by Django 5.2.8 on 2025-12-16 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0012_remove_instructorprofile_hourly_rate_and_more'),
        ('reviews', '0003_remove_review_booking_review_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='instructors.instructorprofile'),
        ),
    ]
