# Generated by Django 5.2.8 on 2025-12-17 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0012_remove_instructorprofile_hourly_rate_and_more'),
        ('listings', '0006_alter_listing_currency'),
        ('providers', '0008_remove_providerprofile_logo_and_more'),
        ('reviews', '0004_review_instructor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('provider__isnull', False)), fields=('reviewer', 'provider'), name='unique_review_per_user_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('instructor__isnull', False)), fields=('reviewer', 'instructor'), name='unique_review_per_user_per_instructor'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('listing__isnull', False)), fields=('reviewer', 'listing'), name='unique_review_per_user_per_listing'),
        ),
    ]
