# Generated by Django 5.2.8 on 2025-12-10 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('instructor', models.CharField(blank=True, max_length=255, null=True)),
                ('max', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('level', models.CharField(blank=True, default='', max_length=100)),
                ('source', models.CharField(default='Walk-in', max_length=20)),
                ('waiver', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='calendar.session')),
            ],
        ),
    ]
