# Generated by Django 5.2.8 on 2025-12-10 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0001_initial'),
        ('providers', '0007_providerprofile_iban_providerprofile_tax_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='provider_id',
        ),
        migrations.AddField(
            model_name='session',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='providers.providerprofile'),
        ),
    ]
