# Generated by Django 5.2.8 on 2025-12-02 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('certifications', models.TextField(blank=True, help_text='List of certs (IKO, PADI)')),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('languages', models.JSONField(default=list)),
                ('country_name', models.CharField(blank=True, max_length=100)),
                ('sports', models.JSONField(default=list)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('stripe_connect_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructors', to='locations.city')),
            ],
        ),
    ]
