# Generated by Django 5.2.8 on 2025-12-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_alter_instructorprofile_city_and_more'),
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='sports',
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='instructors', to='listings.sport'),
        ),
    ]
