# Generated by Django 5.2.8 on 2025-12-05 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0005_remove_instructorprofile_sports_and_more'),
        ('providers', '0005_merchantprofile_providerprofile_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='merchant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to='providers.merchantprofile'),
        ),
    ]
