# Generated by Django 5.2.8 on 2025-12-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0006_instructorprofile_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Commission percentage (15 for subscribed instructors, 25 for default).', max_digits=4),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='is_subscribed',
            field=models.BooleanField(default=False, help_text='If True → instructor receives lower commission rate (15%).'),
        ),
    ]
