# Generated by Django 5.2.8 on 2025-12-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0007_instructorprofile_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='iban',
            field=models.CharField(blank=True, help_text='Bank IBAN for receiving manual payouts', max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='tax_name',
            field=models.CharField(blank=True, help_text='Legal name for invoices and payouts', max_length=255, null=True),
        ),
    ]
