# Generated by Django 5.2.8 on 2025-12-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0008_instructorprofile_iban_instructorprofile_tax_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
