# Generated by Django 5.2.8 on 2025-12-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0009_alter_instructorprofile_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
