# Generated by Django 5.2.8 on 2025-12-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0010_instructorprofile_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text='Public name shown on instructor profile', max_length=255),
        ),
    ]
