# Generated by Django 5.2.8 on 2025-12-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0011_instructorprofile_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='hourly_rate',
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number for the instructor', max_length=50, null=True),
        ),
    ]
