# Generated by Django 5.2.8 on 2025-12-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0012_remove_instructorprofile_hourly_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='iban',
        ),
    ]
