# Generated by Django 5.2.8 on 2025-12-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0013_remove_instructorprofile_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='legal_documents',
            field=models.FileField(blank=True, help_text='Legal or certification documents uploaded for verification', null=True, upload_to='instructors/documents/'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='stripe_connect_id',
            field=models.CharField(blank=True, help_text='DEPRECATED — Stripe Connect ID now lives in MerchantProfile', max_length=100, null=True),
        ),
    ]
