# Generated by Django 5.2.8 on 2025-12-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0014_instructorprofile_legal_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
