# Generated by Django 5.2.8 on 2025-12-08 07:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
        ('payments', '0001_initial'),
        ('providers', '0006_providerprofile_is_subscribed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('method', models.CharField(choices=[('MANUAL', 'Manual Bank Transfer'), ('STRIPE', 'Stripe Transfer')], default='MANUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_payouts', to='bookings.booking')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='providers.providerprofile')),
            ],
        ),
    ]
