# Generated by Django 5.2.8 on 2025-12-10 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0002_merchantpayout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantpayout',
            name='merchant',
        ),
        migrations.AddField(
            model_name='merchantpayout',
            name='merchant_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payout_merchants', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='merchantpayout',
            name='merchant_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
