# Generated by Django 5.2.8 on 2025-12-22 07:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_merchantpayout_merchant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumSignupIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checkout_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('PROVIDER', 'Provider'), ('INSTRUCTOR', 'Instructor')], max_length=20)),
                ('email', models.EmailField(help_text='Email used during Stripe checkout', max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CONSUMED', 'Consumed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('stripe_event_id', models.CharField(blank=True, help_text='Stripe webhook event that confirmed payment', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
