# Generated by Django 5.2.8 on 2025-12-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_premiumsignupintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpayout',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, help_text='Stripe Transfer ID created after capture', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='merchantpayout',
            name='method',
            field=models.CharField(choices=[('MANUAL', 'Manual Bank Transfer'), ('STRIPE', 'Stripe Transfer')], default='STRIPE', max_length=20),
        ),
    ]
