# Generated by Django 5.2.8 on 2025-12-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_merchantpayout_stripe_transfer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantpayout',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final TTW commission for this payout', max_digits=10),
        ),
        migrations.AddField(
            model_name='merchantpayout',
            name='total_charged',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final amount charged to the customer after completion', max_digits=10),
        ),
    ]
