# Generated by Django 5.2.8 on 2025-12-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approved by ops / partners after document review'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_documents_submitted',
            field=models.BooleanField(default=False, help_text='Whether required legal documents were uploaded'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_profile_complete',
            field=models.BooleanField(default=False, help_text='Whether required onboarding fields are completed'),
        ),
    ]
