# Generated by Django 5.2.8 on 2025-12-04 10:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='physical_intensity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='listing',
            name='technical_grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='universal_level',
            field=models.CharField(default='BEGINNER', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='locations.city'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(default='USD', max_length=5),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('SESSION', 'Session'), ('COURSE', 'Course'), ('EXPERIENCE', 'Experience'), ('RENT', 'Rent'), ('TRIP', 'Trip')], max_length=20),
        ),
    ]
