# Generated by Django 5.2.8 on 2025-12-05 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_location_listing_physical_intensity_and_more'),
        ('providers', '0004_remove_providerprofile_sports_providerprofile_sports'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='providers.providerprofile'),
        ),
    ]
