# Generated by Django 5.2.8 on 2025-12-05 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_provider'),
        ('providers', '0005_merchantprofile_providerprofile_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='provider',
        ),
        migrations.AddField(
            model_name='listing',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='providers.merchantprofile'),
        ),
    ]
