# Generated by Django 5.2.8 on 2025-12-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_listing_provider_listing_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(default='EUR', max_length=5),
        ),
    ]
