# Generated by Django 5.2.8 on 2025-12-18 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='address',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='location',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='listing',
            name='physical_intensity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(5)]),
        ),
    ]
