# Generated by Django 5.2.8 on 2025-12-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_listing_address_remove_listing_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='physical_intensity',
            field=models.IntegerField(default=1),
        ),
    ]
