# Generated by Django 5.2.8 on 2025-12-09 13:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_seen_at_message_seen_by_merchant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='seen_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='seen_by_merchant',
        ),
        migrations.RemoveField(
            model_name='message',
            name='seen_by_user',
        ),
        migrations.CreateModel(
            name='MessageSeen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_records', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['seen_at'],
                'unique_together': {('message', 'user')},
            },
        ),
    ]
