# Generated by Django 5.2.8 on 2025-12-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
