# Generated by Django 5.2.8 on 2025-12-10 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_currency'),
        ('calendar', '0002_remove_session_provider_id_session_auto_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='calendar.session'),
        ),
    ]
