# Generated by Django 5.2.8 on 2025-12-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='adjusted_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final amount after partial completion or adjustment', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='adjustment_reason',
            field=models.TextField(blank=True, help_text='Reason for partial completion or cancellation'),
        ),
        migrations.AddField(
            model_name='booking',
            name='completion_percentage',
            field=models.PositiveIntegerField(blank=True, help_text='Declared completion percentage (0–100)', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_authorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('AUTHORIZED', 'Payment Authorized'), ('PAID', 'Payment Captured'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
