# Generated by Django 5.2.8 on 2025-12-23 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_cancelled_at_booking_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('BOOKING_FINALIZED', 'Booking Finalized'), ('BOOKING_PARTIAL', 'Booking Partially Completed'), ('BOOKING_CANCELLED', 'Booking Cancelled')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type'], name='bookings_ad_type_0a3e88_idx'), models.Index(fields=['is_read'], name='bookings_ad_is_read_8090f5_idx'), models.Index(fields=['created_at'], name='bookings_ad_created_a3fe44_idx')],
            },
        ),
    ]
