# Generated by Django 5.2.8 on 2025-12-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount_captured',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount captured from the customer after completion', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='platform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final platform commission based on captured amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final payout amount for provider based on captured amount', max_digits=10, null=True),
        ),
    ]
