# Generated by Django 5.2.8 on 2025-12-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_amount_captured_booking_platform_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='authorized_emails_sent_at',
            field=models.DateTimeField(blank=True, help_text='When booking authorized emails were enqueued/sent', null=True),
        ),
    ]
