# Generated by Django 5.2.8 on 2025-12-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_authorized_emails_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='final_emails_sent_at',
            field=models.DateTimeField(blank=True, help_text='When booking finalized emails were enqueued/sent', null=True),
        ),
    ]
