# Generated by Django 5.2.8 on 2026-01-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_final_emails_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='authorized_emails_sent_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='authorized_admin_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When booking authorized email was sent to admin/support', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='authorized_provider_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When booking authorized email was sent to the provider', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='authorized_user_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When booking authorized email was sent to the user', null=True),
        ),
    ]
