# Generated by Django 5.2.8 on 2026-01-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_remove_booking_authorized_emails_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('AUTHORIZED', 'Payment Authorized'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='AUTHORIZED', max_length=20),
        ),
    ]
