# Generated by Django 5.2.8 on 2026-01-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='estimated_platform_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated platform fee before finalization', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='estimated_provider_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated provider payout before finalization', max_digits=10, null=True),
        ),
    ]
