# Generated by Django 5.2.8 on 2025-12-02 09:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('action_link', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_connect_id', models.CharField(blank=True, help_text='Stripe Connected Account ID', max_length=100, null=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.2, help_text='0.20 = 20%', max_digits=4)),
                ('company_name', models.CharField(max_length=100)),
                ('logo', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('banner_image', models.URLField(blank=True, null=True)),
                ('legal_documents', models.FileField(blank=True, null=True, upload_to='providers/docs/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('auto_accept_bookings', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
