# Generated by Django 5.2.8 on 2025-12-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='sports',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
