# Generated by Django 5.2.8 on 2025-12-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
        ('providers', '0003_providerprofile_id_number_providerprofile_sports_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='sports',
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='sports',
            field=models.ManyToManyField(blank=True, related_name='providers', to='listings.sport'),
        ),
    ]
