# Generated by Django 5.2.8 on 2025-12-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0005_merchantprofile_providerprofile_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='is_subscribed',
            field=models.BooleanField(default=False, help_text='If True → commission_rate becomes 15%. If False → 25%.'),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Commission percentage (15 for subscribed providers, 25 for normal providers)', max_digits=4),
        ),
    ]
