# Generated by Django 5.2.8 on 2025-12-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_providerprofile_iban_providerprofile_tax_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='logo',
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
