# Generated by Django 5.2.8 on 2025-12-23 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_remove_providerprofile_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerprofile',
            name='iban',
        ),
    ]
