# Generated by Django 5.2.8 on 2025-12-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_remove_providerprofile_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='stripe_connect_id',
            field=models.CharField(blank=True, help_text='DEPRECATED — Stripe Connect ID now lives in MerchantProfile', max_length=100, null=True),
        ),
    ]
